version: '3'

services:
  write-db:
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  read-db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
  event-store:
    image: mongo:6.0.4
    ports:
      - '27018:27017'
    environment:
      MONGO_EVENTSDB_DATABASE: ${MONGO_EVENTSDB_DATABASE}
    command: mongod --replSet event-mongo-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongo-data:
